
---
title: "Metrics"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill

---

```{r setup, include=FALSE}
library(flexdashboard)
# R Example Dashboard. No real data is used. All variables are generic and not related to any specific project.
```

```{r results="asis"}
cat("
<style>
#title
{
   color:steelblue;
}
</style>
")
```



  
Overview
=====================================  
    
Column {data-width=600}
-------------------------------------
    
### **Sankey** 

```{r, fig.width=10, fig.height=7}
 library(networkD3)
nodes = data.frame("name" = 
                     c(
                       "A", # 0
                       "B", # 1
                       "C", # 2
                       "D", # 3
                       "E", # 4
                       "F" # 5
                       ))


links = as.data.frame(matrix(c(
  0, 1, 300,
  0, 2, 200, 
  1, 3, 60,
  1, 4, 160,
  1, 5, 80
  ),
  byrow = TRUE, ncol = 3))
names(links) = c("source", "target", "value")

sankeyNetwork(Links = links, Nodes = nodes,
              Source = "source", Target = "target",
              Value = "value", NodeID = "name",
              colourScale = JS('d3.scaleOrdinal(["grey", "steelblue", "orange", "steelblue", "orange"]);'),
              fontSize= 16, fontFamily="Arial", nodeWidth = 30)

detach(package:networkD3)

```  


   
Column {data-width=400}
-------------------------------------

### people had x
    
```{r}
articles <- '400'
valueBox(articles, icon = "glyphicon-user")
```


### of those people had y
    
```{r}
articles <- '60%'
valueBox(articles, icon = "fa-keyboard-o")
```


### people had z


```{r}
articles <- '180'
valueBox(articles, icon = "fa-thumbs-o-up")



```

 


Key Metrics 
=====================================     
   
Column {data-width=333}
-------------------------------------

### **Metric 1**

```{r}
metric1 <- data.frame(test_grp=rep(c("Group1", "Group2"), each=5),
                week=rep(c("(1) 1-Jan", "(2) 8-Jan", "(3) 15-Jan","(4) 22-Jan","(5) 29-Jan"),2),
                vals=c(13,85,24,75,32,79,43,78,22,66))

library(ggplot2)
# Basic line plot without points
ggplot(data=metric1,aes(x=week, y=vals, group=test_grp)) + labs(x = "Test Week", y="Metric 1 vals") + geom_line(aes(color=test_grp))+
    ylim(0, 100) +scale_color_manual(values=c("orange", "steelblue")) +
  theme(legend.position="bottom") + theme_classic()


```

### Metric 2 **


Column {data-width=333} 
-------------------------------------

### **Metric 3**


### **Metric 4**


Column {data-width=333} 
-------------------------------------

### **Metric 5** 

```{r}
library(ggplot2)
 
# create a dataset
num_items=c(rep("0 items" , 3) , rep("1 item" , 3) , rep("2 items" , 3) , rep("3 or more items" , 3) )
test_group=rep(c("G1" , "G2", "G3") , 4)
value=c(0,15,14,
        85,43,48,
        11,21,20,
        4,21,18)
data=data.frame(num_items,test_group,value)
 
# Grouped
ggplot(data, aes(fill=test_group, y=value, x=num_items)) + 
    geom_bar(position="dodge", stat="identity")+scale_fill_manual(values=c("orange", "steelblue","grey")) + theme_classic()

```

### **Metric 6**


```{r}
```

Site Details
=====================================  

Column {data-width=650} 
-------------------------------------

### **Map**: Map of Sites

```{r,}

library(leaflet)
library(rgdal)
library(shiny)
library(readr)
library(zoo)

#mongo
#library(rmongodb)
#date
library(lubridate)
library(zoo)
library(timeDate)
#visualisation
library(ggplot2)
library(RColorBrewer)
library(scales)
library(googleVis)
#data management
library(dplyr)
library(reshape2)
library(tidyr)
#dynamic reporting
library(data.table)
#library(DT)
library(xtable)
library(knitr)



#getwd()
Sites_Ref <- read.csv("~/Home/Sites_Ref_Dummy_Data.csv")

m <- leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addCircleMarkers(Sites_Ref$Long, Sites_Ref$Lat, radius =Sites_Ref$cases/6 , fillColor = "steelblue", stroke = "grey", 
                   fillOpacity= 0.5, popup = paste("<b><font size=4>",Sites_Ref$site_name_proper,"</b><br>",
                                                   "<font size=3> Text1",Sites_Ref$cases, "<br>",
                                                    "Text2 ",Sites_Ref$success)) 
#%>%
#map.fitBounds(group.getBounds()))
m# Print the map

detach(package:leaflet)


```



Column {data-width=350} 
-------------------------------------

### **Attempts:** 



```{r}
library(plotly)
plot_ly(x = c(20, 30, 80, 50, 60), y = c('A  ', 'B  ', 'C  ','D  ', 'E  '), type = 'bar', orientation = 'h',marker = list(color = 'steelblue'))

```


### **Success:**

```{r}
library(plotly)



y <- c('A',
       'B',
       'C',
       'D',
       'E')
x1 <- c(70, 60, 40, 80, 10)
x2 <-c(20, 10, 20, 5, 50)
x3 <- c(10, 30, 40, 15, 40)


success <- data.frame(y, x1, x2, x3)

top_labels <- c('outcome1', 'outcome2', 'outcome3')



plot_ly(success, x = ~x1, name='outcome1', y = ~y, type = 'bar', orientation = 'h',
        marker = list(color = 'steelblue',
                      line = list(color = 'white', width = 1))) %>%
  add_trace(x = ~x2, name='outcome2', marker = list(color = 'grey')) %>%
  add_trace(x = ~x3, name='outcome3', marker = list(color = 'orange')) %>%
  

  

  layout(xaxis = list(title = "",
                      showgrid = FALSE,
                      showline = FALSE,
                      showticklabels = FALSE,
                      zeroline = FALSE,
                      domain = c(0.15, 1)),
         yaxis = list(title = "",
                      showgrid = FALSE,
                      showline = FALSE,
                      showticklabels = FALSE,
                      zeroline = FALSE),
         barmode = 'stack',
         paper_bgcolor = 'white', plot_bgcolor = 'white',
         margin = list(l = 10, r = 10, t = 10, b = 10),
         showlegend = TRUE) %>%
  # labeling the y-axis
  add_annotations(xref = 'paper', yref = 'y', x = 0.14, y = y,
                  xanchor = 'right',
                  text = y,
                  font = list(family = 'Arial', size = 12,
                            color = 'rgb(67, 67, 67)'),
                  showarrow = FALSE, align = 'right') %>%
  # labeling the percentages of each bar (x_axis)
  add_annotations(xref = 'x', yref = 'y',
                  x = x1 / 2, y = y,
                  text = paste(success[,"x1"], '%'),
                  font = list(family = 'Arial', size = 12,
                            color = 'white'),
                  showarrow = FALSE) %>%
  add_annotations(xref = 'x', yref = 'y',
                  x = x1 + x2 / 2, y = y,
                  text = paste(success[,"x2"], '%'),
                  font = list(family = 'Arial', size = 12,
                              color = 'white'),
                  showarrow = FALSE) %>%
  add_annotations(xref = 'x', yref = 'y',
                  x = x1 + x2 + x3 / 2, y = y,
                  text = paste(""), #paste(success[,"x3"], '%'),
                  font = list(family = 'Arial', size = 12,
                              color = 'white'),
                  showarrow = FALSE) 
 
```   
